language: node_js
node_js:
  - lts/*
install:
  npm install
script:
  npx webpack
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/
  repo: deojs/deojs.github.io
  on:
    branch: master